= Keyboard library for Arduino for all languages and keys mapping =

This library allows an Arduino board with USB functions to act as a keyboard. 
The following languages are integrated: English, German, Russian, French, Greek, Hebrew, Italian, Georgian

This library library works like this: you connect a language file and from the moment you can send texts in this language to the computer via HID keyboard emulation. The language file contains all utf-8 characters of the respective language. The position of the characters corresponds to the HID scancode of the keys. Your text is decomposed into individual characters and for each character the scan code is found in the language file, after which the scan code is sent to the computer. 
The language file can be generated automatically. So almost every language can be recorded.

Restriction in use
The principle of the library does not allow printing of characters that are generated by successive pressing of two keys.

For more information about this library please visit us at
https://www.arduino.cc/reference/en/language/functions/usb/keyboard/

== License ==

Copyright (c) Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
